version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_DB=projeto
      - POSTGRES_USER=projeto
      - POSTGRES_PASSWORD=projeto
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      projeto-network:
        ipv4_address: 172.18.0.2

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=amandajuchem@hotmail.com
      - PGADMIN_DEFAULT_PASSWORD=03129686550
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      projeto-network:
        ipv4_address: 172.18.0.3

  projeto-backend:
    image: edsonisaac/projeto-backend:latest
    restart: unless-stopped
    depends_on:
      - postgres
      - pgadmin
    environment:
      - POSTGRES_URL=jdbc:postgresql://172.18.0.2:5432/projeto
      - POSTGRES_USER=projeto
      - POSTGRES_PASSWORD=projeto
    ports:
      - "8080:8080"
    volumes:
      - projeto-backend-data:/var/lib/projeto-backend
    networks:
      projeto-network:
        ipv4_address: 172.18.0.4

  projeto-frontend:
    image: edsonisaac/projeto-frontend:latest
    restart: unless-stopped
    depends_on:
      - postgres
      - pgadmin
      - projeto-backend
    ports:
      - "80:80"
    volumes:
      - projeto-frontend-data:/var/lib/projeto-frontend
    networks:
      projeto-network:
        ipv4_address: 172.18.0.5

volumes:
  postgres-data:
  pgadmin-data:
  projeto-backend-data:
  projeto-frontend-data:

networks:
  projeto-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
