jwt:
  expiration: 43200000
  secret: zE)*wwRHJ=Dr:jvqC6w)VTDpif1}Xbw>GY}#E!R=6#agoK8XgJmgAxqyU^8!-qdsV

spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: password
    username: sa
    url: jdbc:h2:mem:database-test
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
  web:
    locale: pt_BR