jwt:
  expiration: 43200000
  secret: zE)*wwRHJ=Dr:jvqC6w)VTDpif1}Xbw>GY}#E!R=6#agoK8XgJmgAxqyU^8!-qdsV

server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: projeto
    url: jdbc:postgresql://localhost/projeto-api-test
    username: projeto
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
  web:
    locale: pt_BR