app:
  security:
    rsa:
      public-key: classpath:certs/public.pem
      private-key: classpath:certs/private.pem

spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: password
    username: sa
    url: jdbc:h2:mem:database-test
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
  web:
    locale: pt_BR